### PR TITLE
Ros2 galactic port

### PR DESCRIPTION
**Pull request by AlexKaravaev**
Description
----
Hi!

I decided to push my efforts of porting this package to ros2. I am creating now draft pull request, just so my progress would be visible and maybe this way I would not reinvent the wheel :) **Also, please, could you create a branch ros2 in your upstream repo? And also in libchamp repo, champ_teleop and yocs_velocity_smoother.** Setting it to master for now.

- [x] Port libchamp. Here I will insert the link to corresponding PR in libchamp
- [ ] Port velocity smoother.
- [x] Working Gazebo empty world, without velocity control, just standing still robot with effort controllers centered.
- [x] Working rviz only demo.
- [ ] Working Gazebo with teleop robot.
- [ ] Working Gazebo demo with SLAM.
- [ ] Working Gazebo demo with nav2 integration.
- [ ] Code clean-up and refactoring.
- [ ] Testing with real robot. Since I don't have one, I would have this point out of the scope of this current issue and focus solely on gazebo port.

Known difficulties and issues
----
* ros2_controllers official upstream repo doesn't have effort controller implemented yet. Right now sticked to [ros2-controllers repo](https://github.com/rohitmenon86/ros2_controllers). See [issue](https://github.com/ros-controls/ros2_controllers/pull/225).
* I have tried to set-up gazebo ignition simulation, but somehow I can not get RTF more that 0.1. Given that in gazebo classic it runs smoothly with 1.0 RTF,  I recalled that it's something with ignition and moved forward.

### CODE REVIEW

**Comment by AlexKaravaev** [comment]
Here is quick video demo of what I've ported so far

https://user-images.githubusercontent.com/30314738/170779523-a6bb573e-c88a-4051-9eda-d7c2746dd4bd.mov


https://user-images.githubusercontent.com/30314738/170779633-9a349005-1782-4ba2-aaa7-53f2b9fda7c8.mov

**Comment by grassjelly** [comment]
Hi @AlexKaravaev , thanks for this PR. Created a new ros2 branch. Did the same for libchamp. Thank you!

**Comment by grassjelly** [comment]
Hey @jediofgever . Could be point no. 1 be the same issue you’re encountering? 

> ## Description
> Hi!
> 
> I decided to push my efforts of porting this package to ros2. I am creating now draft pull request, just so my progress would be visible and maybe this way I would not reinvent the wheel :) **Also, please, could you create a branch ros2 in your upstream repo? And also in libchamp repo, champ_teleop and yocs_velocity_smoother.** Setting it to master for now.
> 
> * [x]  Port libchamp. Here I will insert the link to corresponding PR in libchamp
> * [ ]  Port velocity smoother.
> * [x]  Working Gazebo empty world, without velocity control, just standing still robot with effort controllers centered.
> * [x]  Working rviz only demo.
> * [ ]  Working Gazebo with teleop robot.
> * [ ]  Working Gazebo demo with SLAM.
> * [ ]  Working Gazebo demo with nav2 integration.
> * [ ]  Code clean-up and refactoring.
> * [ ]  Testing with real robot. Since I don't have one, I would have this point out of the scope of this current issue and focus solely on gazebo port.
> 
> ## Known difficulties and issues
> * ros2_controllers official upstream repo doesn't have effort controller implemented yet. Right now sticked to [ros2-controllers repo](https://github.com/rohitmenon86/ros2_controllers). See [issue](https://github.com/ros-controls/ros2_controllers/pull/225).
> * I have tried to set-up gazebo ignition simulation, but somehow I can not get RTF more that 0.1. Given that in gazebo classic it runs smoothly with 1.0 RTF,  I recalled that it's something with ignition and moved forward.

Hey @jediofgever . Could be point no. 1 be the same issue you’re encountering?

**Comment by jediofgever** [comment]
@grassjelly , I think that is a possibility, [this](https://github.com/jediofgever/quadruped_ros2/blob/main/champ_bringup/config/ros2_control.yaml) is what I use for ros2 control config. The type is `joint_trajectory_controller/JointTrajectoryController`, as I recall in ros1, this was `effort_controllers/JointTrajectoryController`

**Review by jediofgever — COMMENTED** [review]
This is a very nicely done port, congrats!. I did a similar effort to port champ to ROS2 though with some quick&dirty practice. I see that you are spawning `joint_trajectory_controller/JointTrajectoryController` in gazebo.launch.py, could you post a short video of resulting behaviour in Gazebo, in my case the robot behaves quite weirdly as in [here](https://github.com/chvmp/champ/issues/44#issuecomment-1133066417),

**Comment by AlexKaravaev** [comment]
@jediofgever Oh I haven't seen that you actually started porting it ros2 already, awesome work! We definetely can somehow merge your one and this one into one.  

As for joint_trajectory_controller/JointTrajectoryController I haven't yet tried the gait with gazebo. But you can observe behavior without gate, just using manual joint control in the video above. 

Are you using ignition gazebo or classic one? I observed very strange behavior in ignition and finally switched to classic

**Comment by AlexKaravaev** [comment]
@grassjelly hi! This PR wasn't finished yet. Do you think it's better to open new one?

**Comment by grassjelly** [comment]
hey yes pls

**Pull request merged**
